version: "3"
services:
  kong:
    build: .
    environment:
        - KONG_DATABASE=off
        - KONG_GO_PLUGINS_DIR=/app/go-plugins
        - KONG_DECLARATIVE_CONFIG=/home/kong/config.yml
        - KONG_PLUGINS=bundled,my-plugin
        - KONG_PLUGINSERVER_NAMES=my-plugin
        - KONG_PLUGINSERVER_MY_PLUGIN_START_CMD=/app/go-plugins/my-plugin
        - KONG_PLUGINSERVER_MY_PLUGIN_QUERY_CMD=/app/go-plugins/my-plugin -dump
        - KONG_PROXY_LISTEN=0.0.0.0:8000
        - KONG_ADMIN_LISTEN=0.0.0.0:8001
        - KONG_LOG_LEVEL=debug
        - KONG_PROXY_ACCESS_LOG=/dev/stdout
        - KONG_ADMIN_ACCESS_LOG=/dev/stdout
        - KONG_PROXY_ERROR_LOG=/dev/stderr
        - KONG_ADMIN_ERROR_LOG=/dev/stderr
    volumes:
        - ./config.yml:/home/kong/config.yml:Z
    ports:
        - '8000:8000'
        - '8001:8001'
        - '8443:8443'
        - '8444:8444'
  konga:
    image: pantsel/konga:latest
    volumes:
      - ./konga/users.js:/app/users.js:Z
      - ./konga/nodes.js:/app/nodes.js:Z
    environment:
      - NODE_ENV=development
      - KONGA_SEED_USER_DATA_SOURCE_FILE=/app/users.js
      - KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE=/app/nodes.js
    ports:
      - "1337:1337/tcp"
    links:
      - kong
  echo:
    image: ealen/echo-server
